version: "3"
services:
  webapp-1:
    build: ./webapp
    environment:
      PORT: 8080
      INDEX: 1
  webapp-2:
    build: ./webapp
    environment:
      PORT: 8080
      INDEX: 2
  reverse-proxy:
    build: ./reverse-proxy
    ports:
      - 8080:80
