version: '2'
services:
  webapp-1:
    build: ./webapp
    networks:
      - default
    environment:
      PORT: 8080
  reverse-proxy:
    build: ./reverse-proxy
    networks:
      - default
    ports:
      - 8080:80
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
          aux_addresses:
            webapp-1: 10.5.0.5
            reverse-proxy: 10.5.0.6
